// This file is a filtered file of the items
/* Item Ammounts and types:
    Beer: 8, [IPA, lager, stout, ale]
    Spirits:8 , [whisky, tequila, vodka (Okryddad sprit), rum (rom)]
    Wine:8  [Red wine (R\u00c3\u00b6tt vin, Mjukt & B\u00c3\u00a4rigt), white wine (Vitt vin)]
    alcohol free: 6 [Alkoholfritt]
    Total: 30

*/
var DB_FILTERED = [
    {
        "nr": "1104803",
        "articleid": "722671",
        "articletype": "11048",
        "name": "Suruga Bay",
        "name2": "Imperial IPA",
        "priceinclvat": "59.90",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2013-04-02",
        "finaldelivery": " ",
        "catgegory": "\u00c3\u2013l, Ale",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "",
        "countryoforiginlandname": "Japan",
        "producer": "Baird Brewing Co",
        "provider": "Cask Sweden AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "7.5%",
        "module": "T7",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    },
    {
        "nr": "1104903",
        "articleid": "722706",
        "articletype": "11049",
        "name": "Rising Sun",
        "name2": "Pale Ale",
        "priceinclvat": "59.90",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2013-04-02",
        "finaldelivery": " ",
        "catgegory": "\u00c3\u2013l, Ale",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "",
        "countryoforiginlandname": "Japan",
        "producer": "Baird Brewing Co",
        "provider": "Cask Sweden AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "5%",
        "module": "",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    },
    {
        "nr": "1105003",
        "articleid": "722713",
        "articletype": "11050",
        "name": "Shimaguni",
        "name2": "Stout",
        "priceinclvat": "59.90",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2013-04-02",
        "finaldelivery": " ",
        "catgegory": "\u00c3\u2013l, Porter och Stout",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "",
        "countryoforiginlandname": "Japan",
        "producer": "Baird Brewing Co",
        "provider": "Cask Sweden AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "4.5%",
        "module": "",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    },
    {
        "nr": "1105303",
        "articleid": "723445",
        "articletype": "11053",
        "name": "Uinta Baba Black Lager",
        "name2": "",
        "priceinclvat": "27.90",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2013-03-01",
        "finaldelivery": " ",
        "catgegory": "\u00c3\u2013l, M\u00c3\u00b6rk lager",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "",
        "countryoforiginlandname": "USA",
        "producer": "Uinta Brewing Company",
        "provider": "AB Wicked Wine Sweden",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "4%",
        "module": "T6",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    },
    {
        "nr": "1105603",
        "articleid": "723541",
        "articletype": "11056",
        "name": "Vuur & Vlam",
        "name2": "IPA",
        "priceinclvat": "26.90",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2013-02-01",
        "finaldelivery": " ",
        "catgegory": "\u00c3\u2013l, Ale",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "",
        "countryoforiginlandname": "Nederl\u00c3\u00a4nderna",
        "producer": "Brouwerij De Molen",
        "provider": "Galatea Spirits AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "6.2%",
        "module": "T5",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    },
    {
        "nr": "1105703",
        "articleid": "723902",
        "articletype": "11057",
        "name": "Stronzo",
        "name2": "Swagger Juze",
        "priceinclvat": "46.90",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2013-03-01",
        "finaldelivery": " ",
        "catgegory": "\u00c3\u2013l, Porter och Stout",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "",
        "countryoforiginlandname": "Danmark",
        "producer": "Stronzo Brewing Co",
        "provider": "Elixir HB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "8%",
        "module": "",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    },
    {
        "nr": "1105901",
        "articleid": "724472",
        "articletype": "11059",
        "name": "Ichtegems",
        "name2": "Grand Cru Cuv\u00c3\u00a9e",
        "priceinclvat": "63.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2013-04-02",
        "finaldelivery": " ",
        "catgegory": "\u00c3\u2013l, Ale",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "",
        "countryoforiginlandname": "Belgien",
        "producer": "Brouwerij Strubbe",
        "provider": "Belgodeli",
        "productionyear": "2010",
        "testedproductionyear": "2010",
        "alcoholstrength": "6.5%",
        "module": "T5",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    },
    {
        "nr": "1106901",
        "articleid": "730955",
        "articletype": "11069",
        "name": "The Sinner Series Sloth",
        "name2": "Amager",
        "priceinclvat": "44.90",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2013-03-01",
        "finaldelivery": " ",
        "catgegory": "\u00c3\u2013l, Ale",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "",
        "countryoforiginlandname": "Danmark",
        "producer": "Amager Bryghus",
        "provider": "Elixir HB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "6%",
        "module": "",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    },
    {
        "nr": "1024601",
        "articleid": "560847",
        "articletype": "10246",
        "name": "The Whisky Agency",
        "name2": "Laphroaig",
        "priceinclvat": "725.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2011-03-15",
        "finaldelivery": " ",
        "catgegory": "Whisky, Malt",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "Skottland, Islay",
        "countryoforiginlandname": "Storbritannien",
        "producer": "The Whisky Agency",
        "provider": "Origo Wine Import",
        "productionyear": "2000",
        "testedproductionyear": "",
        "alcoholstrength": "52.5%",
        "module": "T7",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    },
    {
        "nr": "1024702",
        "articleid": "560340",
        "articletype": "10247",
        "name": "Mortlach",
        "name2": "Cask 2310",
        "priceinclvat": "583.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2011-05-02",
        "finaldelivery": " ",
        "catgegory": "Whisky, Malt",
        "packaging": "Flaska",
        "captype": "Naturkork",
        "countryoforigin": "Skottland, Highlands, Speyside",
        "countryoforiginlandname": "Storbritannien",
        "producer": "Gordon & MacPhail",
        "provider": "Symposion International AB",
        "productionyear": "1984",
        "testedproductionyear": "",
        "alcoholstrength": "46%",
        "module": "",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    },
    {
        "nr": "7048001",
        "articleid": "50203",
        "articletype": "70480",
        "name": "Red Square Vodka",
        "name2": "",
        "priceinclvat": "209.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2004-10-01",
        "finaldelivery": " ",
        "catgegory": "Okryddad sprit",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "",
        "countryoforiginlandname": "Storbritannien",
        "producer": "Halewood International",
        "provider": "Nigab",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "37.5%",
        "module": "",
        "assortment": "BS",
        "organic": "0",
        "kosher": "0"
    },
    {
        "nr": "1001",
        "articleid": "190719",
        "articletype": "10",
        "name": "Vanlig Vodka",
        "name2": "",
        "priceinclvat": "195.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2006-04-01",
        "finaldelivery": " ",
        "catgegory": "Okryddad sprit",
        "packaging": "Flaska",
        "captype": "Skruvkapsyl",
        "countryoforigin": "",
        "countryoforiginlandname": "Sverige",
        "producer": "Svensk Export Vodka AB",
        "provider": "Fondberg",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "37.5%",
        "module": "",
        "assortment": "FS",
        "organic": "0",
        "kosher": "0"
    },
    {
        "nr": "1004901",
        "articleid": "733068",
        "articletype": "10049",
        "name": "Rhum J.M",
        "name2": "",
        "priceinclvat": "1399.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2013-04-02",
        "finaldelivery": " ",
        "catgegory": "Rom, M\u00c3\u00b6rk",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "Martinique",
        "countryoforiginlandname": "Frankrike",
        "producer": "Les Heritiers Crassous de Mede",
        "provider": "Cask Sweden AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "44.8%",
        "module": "T7",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    },
    {
        "nr": "1005602",
        "articleid": "733468",
        "articletype": "10056",
        "name": "Cl\u00c3\u00a9ment",
        "name2": "Single Cask",
        "priceinclvat": "529.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2013-04-02",
        "finaldelivery": " ",
        "catgegory": "Rom, M\u00c3\u00b6rk",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "Martinique",
        "countryoforiginlandname": "Frankrike",
        "producer": "Les Heritiers Crassous de Mede",
        "provider": "Cask Sweden AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "47.6%",
        "module": "T7",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    },
    {
        "nr": "1701",
        "articleid": "215342",
        "articletype": "17",
        "name": "Jos\u00c3\u00a9 Cuervo Especial",
        "name2": "Reposado",
        "priceinclvat": "285.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2006-10-02",
        "finaldelivery": " ",
        "catgegory": "Tequila och Mezcal",
        "packaging": "Flaska",
        "captype": "Skruvkapsyl",
        "countryoforigin": "Jalisco",
        "countryoforiginlandname": "Mexiko",
        "producer": "Cuervo",
        "provider": "Berntson Brands AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "38%",
        "module": "",
        "assortment": "FS",
        "organic": "0",
        "kosher": "0"
    },
    {
        "nr": "30702",
        "articleid": "34305",
        "articletype": "307",
        "name": "Sierra",
        "name2": "Tequila Silver",
        "priceinclvat": "199.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2002-04-02",
        "finaldelivery": " ",
        "catgegory": "Tequila och Mezcal",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "Jalisco",
        "countryoforiginlandname": "Mexiko",
        "producer": "Sierra Destileria",
        "provider": "Nigab",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "38%",
        "module": "",
        "assortment": "FS",
        "organic": "0",
        "kosher": "0"
    },
    {
        "nr": "1279801",
        "articleid": "15536",
        "articletype": "12798",
        "name": "Castillo de Gredos",
        "name2": "White wine",
        "priceinclvat": "55.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "1998-05-04",
        "finaldelivery": " ",
        "catgegory": "Vitt vin,  L\u00c3\u00a4tt & Avrundat",
        "packaging": "Papp",
        "captype": "",
        "countryoforigin": "",
        "countryoforiginlandname": "Spanien",
        "producer": "Bodegas Vinartis",
        "provider": "Prime Wine Sweden AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "12%",
        "module": "",
        "assortment": "FS",
        "organic": "0",
        "kosher": "0"
    },
    {
        "nr": "1279808",
        "articleid": "22290",
        "articletype": "12798",
        "name": "Castillo de Gredos",
        "name2": "White wine",
        "priceinclvat": "139.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2000-03-06",
        "finaldelivery": " ",
        "catgegory": "Vitt vin,  L\u00c3\u00a4tt & Avrundat",
        "packaging": "Box",
        "captype": "Vingtapp",
        "countryoforigin": "",
        "countryoforiginlandname": "Spanien",
        "producer": "Bodegas Vinartis",
        "provider": "Prime Wine Sweden AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "12%",
        "module": "",
        "assortment": "FS",
        "organic": "0",
        "kosher": "0"
    },
    {
        "nr": "7044202",
        "articleid": "708513",
        "articletype": "70442",
        "name": "Coffele Le Sponde",
        "name2": "Recioto di Soave",
        "priceinclvat": "99.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2012-11-01",
        "finaldelivery": " ",
        "catgegory": "Vitt vin, S\u00c3\u00b6tt",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "Venetien, Soave, Recioto di Soave",
        "countryoforiginlandname": "Italien",
        "producer": "Coffele",
        "provider": "Red & White Wine Sweden AB",
        "productionyear": "2010",
        "testedproductionyear": "",
        "alcoholstrength": "12.5%",
        "module": "",
        "assortment": "BS",
        "organic": "0",
        "kosher": "0"
    },
    {
        "nr": "7058101",
        "articleid": "708295",
        "articletype": "70581",
        "name": "Coffele",
        "name2": "Valpolicella",
        "priceinclvat": "136.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2012-11-01",
        "finaldelivery": " ",
        "catgegory": "R\u00c3\u00b6tt vin",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "Venetien, Valpolicella",
        "countryoforiginlandname": "Italien",
        "producer": "Coffele",
        "provider": "Red & White Wine Sweden AB",
        "productionyear": "2011",
        "testedproductionyear": "",
        "alcoholstrength": "12.5%",
        "module": "",
        "assortment": "BS",
        "organic": "0",
        "kosher": "0"
    },
    {
        "nr": "1279701",
        "articleid": "15535",
        "articletype": "12797",
        "name": "Castillo de Gredos",
        "name2": "Red Wine",
        "priceinclvat": "55.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "1998-05-04",
        "finaldelivery": " ",
        "catgegory": "R\u00c3\u00b6tt vin, Mjukt & B\u00c3\u00a4rigt",
        "packaging": "Papp",
        "captype": "",
        "countryoforigin": "",
        "countryoforiginlandname": "Spanien",
        "producer": "Bodegas Vinartis",
        "provider": "Prime Wine Sweden AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "13%",
        "module": "",
        "assortment": "FS",
        "organic": "0",
        "kosher": "0"
    },
    {
        "nr": "1279708",
        "articleid": "22289",
        "articletype": "12797",
        "name": "Castillo de Gredos",
        "name2": "Red Wine",
        "priceinclvat": "129.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2000-02-07",
        "finaldelivery": " ",
        "catgegory": "R\u00c3\u00b6tt vin, Mjukt & B\u00c3\u00a4rigt",
        "packaging": "Box",
        "captype": "Vingtapp",
        "countryoforigin": "",
        "countryoforiginlandname": "Spanien",
        "producer": "Bodegas Vinartis",
        "provider": "Prime Wine Sweden AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "13%",
        "module": "",
        "assortment": "FS",
        "organic": "0",
        "kosher": "0"
    },
    {
        "nr": "3150502",
        "articleid": "344793",
        "articletype": "31505",
        "name": "Linkwood",
        "name2": "Sweet Red Wine Finish 26 Years",
        "priceinclvat": "1399.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2008-11-14",
        "finaldelivery": " ",
        "catgegory": "Whisky, Malt",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "Skottland, Highlands, Speyside",
        "countryoforiginlandname": "Storbritannien",
        "producer": "Linkwood Distillery",
        "provider": "Diageo Sweden AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "55.5%",
        "module": "T9",
        "assortment": "TSE",
        "organic": "0",
        "kosher": "0"
    },
    {
        "nr": "7031901",
        "articleid": "793779",
        "articletype": "70319",
        "name": "Colgin",
        "name2": "IX Estate Red Wine",
        "priceinclvat": "3999.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2013-10-01",
        "finaldelivery": " ",
        "catgegory": "R\u00c3\u00b6tt vin",
        "packaging": "Flaska",
        "captype": "Naturkork",
        "countryoforigin": "Kalifornien, North Coast, Napa Valley",
        "countryoforiginlandname": "USA",
        "producer": "Colgin",
        "provider": "Divine AB",
        "productionyear": "2010",
        "testedproductionyear": "",
        "alcoholstrength": "15%",
        "module": "",
        "assortment": "BS",
        "organic": "0",
        "kosher": "0"
    }, 
    {
        "nr": "190002",
        "articleid": "417665",
        "articletype": "1900",
        "name": "St\u00c3\u00b6rtebeker 1402",
        "name2": "",
        "priceinclvat": "11.90",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2009-12-01",
        "finaldelivery": " ",
        "catgegory": "Alkoholfritt, \u00c3\u2013l",
        "packaging": "Flaska",
        "captype": "",
        "countryoforigin": "",
        "countryoforiginlandname": "Tyskland",
        "producer": "Stralsunder Brauerei",
        "provider": "Heba Food & Beverages AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "0.2%",
        "module": "",
        "assortment": "FS\u00c3\u2013",
        "organic": "1",
        "kosher": "0"
    },
    {
        "nr": "190101",
        "articleid": "401996",
        "articletype": "1901",
        "name": "Loxton",
        "name2": "Semillon Chardonnay",
        "priceinclvat": "48.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2009-10-01",
        "finaldelivery": " ",
        "catgegory": "Alkoholfritt, Vitt",
        "packaging": "Flaska",
        "captype": "Skruvkapsyl",
        "countryoforigin": "",
        "countryoforiginlandname": "Australien",
        "producer": "Loxton Wines",
        "provider": "Spirit of Ward AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "0.2%",
        "module": "",
        "assortment": "FS\u00c3\u2013",
        "organic": "0",
        "kosher": "0"
    },
    {
        "nr": "190201",
        "articleid": "597009",
        "articletype": "1902",
        "name": "Raml\u00c3\u00b6sa",
        "name2": "",
        "priceinclvat": "18.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2011-10-01",
        "finaldelivery": " ",
        "catgegory": "Alkoholfritt, Vatten",
        "packaging": "PET-flaska",
        "captype": "Plastkork\/syntetkork",
        "countryoforigin": "Sk\u00c3\u00a5ne l\u00c3\u00a4n, Helsingborgs stad",
        "countryoforiginlandname": "Sverige",
        "producer": "AB Raml\u00c3\u00b6sa H\u00c3\u00a4lsobrunn",
        "provider": "Carlsberg Sverige AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "0%",
        "module": "",
        "assortment": "FS\u00c3\u2013",
        "organic": "0",
        "kosher": "0"
    },
    {
        "nr": "190312",
        "articleid": "508354",
        "articletype": "1903",
        "name": "Estrella Damm N. A.",
        "name2": "Non-Alcoholic",
        "priceinclvat": "9.50",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2011-01-05",
        "finaldelivery": " ",
        "catgegory": "Alkoholfritt, \u00c3\u2013l",
        "packaging": "Burk",
        "captype": "",
        "countryoforigin": "",
        "countryoforiginlandname": "Spanien",
        "producer": "Damm",
        "provider": "Carlsberg Sverige AB",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "0%",
        "module": "",
        "assortment": "FS\u00c3\u2013",
        "organic": "0",
        "kosher": "0"
    },
    {
        "nr": "190715",
        "articleid": "622011",
        "articletype": "1907",
        "name": "San Miguel",
        "name2": "0,0 %",
        "priceinclvat": "7.90",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2012-04-02",
        "finaldelivery": " ",
        "catgegory": "Alkoholfritt, \u00c3\u2013l",
        "packaging": "Burk",
        "captype": "",
        "countryoforigin": "",
        "countryoforiginlandname": "Spanien",
        "producer": "San Miguel",
        "provider": "Brewery International Sweden A",
        "productionyear": "",
        "testedproductionyear": "",
        "alcoholstrength": "0%",
        "module": "",
        "assortment": "FS\u00c3\u2013",
        "organic": "0",
        "kosher": "0"
    },
    {
        "nr": "190901",
        "articleid": "547367",
        "articletype": "1909",
        "name": "Arc-en-Ciel",
        "name2": "Grenache Syrah",
        "priceinclvat": "45.00",
        "volumeml": null,
        "priceperlitre": null,
        "introduced": "2011-04-01",
        "finaldelivery": " ",
        "catgegory": "Alkoholfritt, R\u00c3\u00b6tt",
        "packaging": "Flaska",
        "captype": "Skruvkapsyl",
        "countryoforigin": "",
        "countryoforiginlandname": "Frankrike",
        "producer": "Providential Wines & Spirits A",
        "provider": "Providential Wines & Spirits A",
        "productionyear": "2011",
        "testedproductionyear": "2011",
        "alcoholstrength": "0.5%",
        "module": "",
        "assortment": "FS\u00c3\u2013",
        "organic": "0",
        "kosher": "0"
    },

]